import { useEffect, useState } from 'react';
import ComercianteSidebar from '../../components/ComercianteSidebar';
import apiClient from '../../services/apiClient';

interface Distrito { idDistrito: number; nombre: string; ciudad: string; costoEnvio: number; }
interface Tarifa { id?: number; distritoId: number; distrito: string; costoEnvio: number; activo: boolean; }

export default function ConfiguracionEnvioPage(){
  const [distritos,setDistritos]=useState<Distrito[]>([]); const [tarifas,setTarifas]=useState<Record<number,Tarifa>>({}); const [guardando,setGuardando]=useState<number|null>(null); const [mensaje,setMensaje]=useState('');
  useEffect(()=>{Promise.all([apiClient.get<Distrito[]>('/distritos'),apiClient.get<Tarifa[]>('/tarifas-envio/mis-tarifas')]).then(([d,t])=>{setDistritos(d.data);setTarifas(Object.fromEntries(t.data.map(x=>[x.distritoId,x])));});},[]);
  async function guardar(d:Distrito){const actual=tarifas[d.idDistrito]??{distritoId:d.idDistrito,distrito:d.nombre,costoEnvio:d.costoEnvio,activo:true};setGuardando(d.idDistrito);setMensaje('');try{const {data}=await apiClient.put<Tarifa>('/tarifas-envio/mis-tarifas',{distritoId:d.idDistrito,costoEnvio:actual.costoEnvio,activo:actual.activo});setTarifas(v=>({...v,[d.idDistrito]:data}));setMensaje(`Tarifa de ${d.nombre} guardada.`);}catch{setMensaje('No se pudo guardar la tarifa.');}finally{setGuardando(null);}}
  return <div className="flex min-h-screen"><ComercianteSidebar/><main className="min-w-0 flex-1 bg-gray-100 p-6 lg:p-8"><h1 className="text-2xl font-bold">Precios de delivery</h1><p className="mt-1 text-sm text-gray-500">Define a qué distritos entregas y el costo que se cobrará en el pago.</p>{mensaje&&<p className="mt-4 rounded-lg bg-white p-3 text-sm">{mensaje}</p>}<div className="mt-6 overflow-x-auto rounded-xl bg-white p-5 shadow-sm"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Distrito</th><th>Ciudad</th><th>Costo (S/)</th><th>Disponible</th><th></th></tr></thead><tbody>{distritos.map(d=>{const t=tarifas[d.idDistrito]??{distritoId:d.idDistrito,distrito:d.nombre,costoEnvio:d.costoEnvio,activo:false};return <tr key={d.idDistrito} className="border-b"><td className="p-3 font-medium">{d.nombre}</td><td>{d.ciudad}</td><td><input type="number" min="0" step="0.10" value={t.costoEnvio} onChange={e=>setTarifas(v=>({...v,[d.idDistrito]:{...t,costoEnvio:Number(e.target.value)}}))} className="w-28 rounded-lg border px-3 py-2"/></td><td><input type="checkbox" checked={t.activo} onChange={e=>setTarifas(v=>({...v,[d.idDistrito]:{...t,activo:e.target.checked}}))}/></td><td><button onClick={()=>void guardar(d)} disabled={guardando===d.idDistrito} className="rounded-lg bg-primario px-4 py-2 font-semibold text-white disabled:opacity-50">Guardar</button></td></tr>})}</tbody></table></div></main></div>;
}
